const pattern = {
    black: '#000',
    aaa: '#aaa',
    eee: '#eee',
    green: 'green',
    tomato: 'tomato',

    human: ["","","","olive","olive","olive","","","","","","","","olive","olive","olive","","","","","","","","olive","olive","olive","","","olive","","","","","","olive","","","","olive","","olive","olive","olive","olive","olive","olive","olive","olive","olive","","olive","","olive","olive","olive","olive","olive","","","","olive","","olive","olive","olive","olive","olive","","","","","","","olive","","olive","","","","","","","","olive","","olive","","olive","","","","","olive","olive","","olive","olive","olive","",""],
    bullet: ["","","","","","","","","","","","","","","","","","","","","","","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","","maroon","gray","gray","gray","black","black","black","black","maroon","maroon","gray","gray","gray","gray","black","black","black","black","maroon","maroon","gray","gray","gray","gray","black","black","black","black","maroon","","maroon","gray","gray","gray","black","black","black","black","maroon","","","maroon","maroon","maroon","maroon","maroon","maroon","maroon","maroon","","","","","","","","","","","","","","","","","","","",""],
    gun: ["","","","","","","","","","","","tomato","tomato","maroon","maroon","maroon","maroon","maroon","maroon","maroon","tomato","black","black","tomato","maroon","maroon","maroon","maroon","maroon","maroon","tomato","black","black","tomato","maroon","maroon","maroon","maroon","maroon","maroon","tomato","black","black","tomato","maroon","maroon","maroon","maroon","maroon","maroon","tomato","black","black","tomato","maroon","maroon","maroon","maroon","maroon","maroon","tomato","black","black","tomato","maroon","maroon","maroon","maroon","maroon","maroon","tomato","tomato","tomato","tomato","maroon","maroon","maroon","maroon","maroon","maroon","","tomato","tomato","maroon","maroon","maroon","maroon","maroon","maroon","maroon","","","","","","","","","",""],
    fire: ["","","","tomato","","","","","tomato","","","","","tomato","","","","tomato","tomato","","","","tomato","tomato","tomato","","","tomato","tomato","","","tomato","tomato","tomato","tomato","tomato","","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","","tomato","tomato","tomato","tomato","tomato","tomato","tomato","tomato","","","","tomato","tomato","tomato","","tomato","tomato","",""],
    turtle: ["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","green","green","green","green","green","green","","","","green","green","gray","gray","green","green","gray","green","","green","gray","gray","green","green","gray","gray","green","green","green","green","gray","gray","green","green","gray","gray","green","green","green","","green","green","gray","gray","green","green","gray","green","","","","green","green","green","green","green","green","","","","","","","","","","","",""],
    star: ["","","","","gold","gold","","","","","","","","gold","gold","gold","gold","","","","","","","gold","gold","gold","gold","","","","","","gold","gold","gold","gold","gold","gold","","","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","","","gold","gold","gold","gold","gold","gold","","","","","","gold","gold","gold","gold","","","","","","","gold","gold","gold","gold","","","","","","","","gold","gold","","","",""],
}